### ISSUE TITLE
Missing precision

### ISSUE THREAD

**Issue by To3No7** [fredrik-johansson/mpmath#636] opened 2022-08-07 11:30 UTC
I have trouble calculating a relatively simple expression "log(8/(2*pi*5*cos(7/5)^2))*(2*5)^(-8)" to the desired precision.

My code

```
import mpmath as mpm
from mpmath import mpf
mpm.dps = 100; # Target (decimal) precision

# Trying to calculate 
mpmmp = mpm.log(8/(2*mpm.pi*5*mpm.cos(7/5)**2))*(2*5)**(-8)
# also tried, but gives the same result:
# mpmmp = mpm.log(mpf(8)/(mpf(2)*mpm.pi*mpf(5)*mpm.cos(mpf(7)/mpf(5))**mpf(2)))*(mpf(2)*mpf(5))**(-mpf(8))
print(N(mpmmp, 50))

# Same thing in Wolfram Alpha https://www.wolframalpha.com/input?i=+log%288%2F%282*pi*5*cos%287%2F5%29%5E2%29%29*%282*5%29%5E%28-8%29
wamp = mpm.mpf("2.1764268381757881245184989320757924235425037995295963369536875540976739004791583229859268345586450088673471866819775813945E-8")
print(N(wamp, 50))

print(N(mpmmp-wamp, 50))
```
With the result
```
0.000000021764268381757866721875713136684360460293419237132
0.000000021764268381757879956765513985127158402832492356538
-1.3234889800848442797942539073119405657052993774414e-23

```
Why do they not match?

**Comment by WarrenWeckesser** [comment] 2022-08-09 17:15
The expression `mpm.log(8/(2*mpm.pi*5*mpm.cos(7/5)**2))*(2*5)**(-8)` includes terms that will be evaluated by Python using 64 bit floating point before being passed through to `mpmath` functions. Specifically, `7/5` will be the 64 bit floating point approximation to 1.4, and `(2*5)**(-8)` will be the 64 bit floating point approximation to `1e-08`.

Try

    mpmmp = mpm.log(8/(2*mpm.pi*5*mpm.cos(mpf(7)/5)**2))*mpf(2*5)**(-8)

(or any other reformulation that avoids floating point calculations with Python floats).

**Comment by To3No7** [comment] 2022-08-09 18:29
As I wrote in a comment I have already tried:
`mpmmp = mpm.log(mpf(8)/(mpf(2)*mpm.pi*mpf(5)*mpm.cos(mpf(7)/mpf(5))**mpf(2)))*(mpf(2)*mpf(5))**(-mpf(8))`
which still gives the same (wrong) result.

Thus I suspect something else is going on.

**Comment by WarrenWeckesser** [comment] 2022-08-09 18:43
> As I wrote in a comment I have already tried:

Sorry!  I guess I skimmed the rest after seeing the mistakes in the code that is not commented out.

The problem is this line:

    mpm.dps = 100; # Target (decimal) precision

It should be

    mpm.mp.dps = 100; # Target (decimal) precision

**Comment by To3No7** [comment] 2022-08-09 18:43
But maybe you are on to something. It seems that the cos(1.4) is problematic...

If I try
```
# https://www.wolframalpha.com/input?i=cos%287%2F5%29
wacos = mpf("0.1699671429002409386167480352036498029281839210285343089823652114946477108519473273490720177139451367906088909932284418441939728")
mpcos = mpm.cos(mpf(7)/mpf(5)) # or more directly
mpcos = mpm.cos(mpf("1.4"))
print(N(mpcos-wacos, 50))
```
I get
`1.1102230246251565404236316680908203125000000000000e-16`

**Comment by To3No7** [comment] 2022-08-09 18:47
Ah, the "mpm.mp.dps = 100" solved it!

So many hours of frustration this has solved!
Many Thanks!

**Comment by WarrenWeckesser** [comment] 2022-08-22 18:13
@To3No7, if your problem is solve, I think you can close this issue.

**Comment by To3No7** [comment] 2022-08-22 20:38
OK, problem solved!

**Closed** 2022-08-22 20:39 UTC
